language: php
php:
  - 7.1

env:
  global:
    - APP_ENV=testing
    - DB_CONNECTION=sqlite_testing

#sudo: false

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

before_script:
  - if [[ "$(php -v | grep 'PHP 7')" ]]; then yes | pecl install -f apcu; fi
#- echo "extension = apc.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enabled=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "apc.enable_cli=1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  - src/vendor/bin/phpunit -c src/phpunit.xml
  #- php .travis-coverage-checker.php src/build/tests-clover.xml 70
