version: '3'

volumes:
    database_data:
        driver: local
    php:

services:
    nginx-proxy:
        container_name: acme_nginx_proxy
        image: jwilder/nginx-proxy
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    nginx:
        image: nginx:latest
        container_name: acme_nginx
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - php:/var/www/acme/src
        depends_on:
            - php
            - mysql
        environment:
            - VIRTUAL_HOST=acme.dev

    php:
        build:
            context: ./docker/php
            args:
                APCU_VERSION: 5.1.8
                APCU_BC_VERSION: 1.0.3
        container_name: acme_php
        expose:
            - 9000
        volumes:
            - ./src:/var/www/acme/src

    testing:
        build: ./docker/php/
        container_name: acme_testing
        volumes:
            - php:/var/www/acme/src

    mysql:
        image: mysql:latest
        container_name: ${MYSQL_HOST}
        restart: "always"
        ports:
          - 8989:3306
        volumes:
            - database_data:/var/lib/mysql
        env_file:
            - "./src/.env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    composer:
        container_name: acme_php_composer
        restart: "no"
        image: composer:latest
        volumes:
            - .:/app
        depends_on:
          - php
