version: '2'

volumes:
    database_data:
        driver: local

services:
    nginx-proxy:
        container_name: acme_nginx_proxy
        image: jwilder/nginx-proxy
        ports:
            - 80:80
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro

    nginx:
        image: nginx:latest
        container_name: acme_nginx
        ports:
            - 8080:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
        environment:
            - VIRTUAL_HOST=acme.dev

    php:
        build:
            context: ./docker/php
            args:
                APCU_VERSION: 5.1.8
                APCU_BC_VERSION: 1.0.3
        container_name: acme_php
        expose:
            - 9000
        volumes:
            - ./src:/var/www/acme/src
        environment:
            MYSQL_ROOT_PASSWORD: fool
            MYSQL_DATABASE: project
            MYSQL_USER: chuck
            MYSQL_PASSWORD: norris
            #XDEBUG_CONFIG: remote_host=172.18.0.2

    testing:
        build: ./docker/php/
        container_name: acme_testing
        volumes_from:
            - php

    mysql:
        image: mysql:latest
        container_name: acme_mysql
        expose:
            - 3306
        volumes:
            - database_data:/var/lib/mysql

    composer:
        container_name: acme_php_composer
        restart: "no"
        image: composer:latest
        volumes:
            - .:/app
        depends_on:
          - php
