# This is a simple docker dev environment.
version: '2'

volumes:
    database_data:
        driver: local

services:
  nginx:
      image: nginx:latest
      container_name: acme_nginx
      ports:
          - 8080:80
      volumes:
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      volumes_from:
          - php

  php:
      build: ./docker/php/
      container_name: acme_php
      expose:
          - 9000
      volumes:
          - .:/var/www/acme

  testing:
      build: ./docker/php/
      container_name: acme_testing
      volumes_from:
          - php

  mysql:
      image: mysql:latest
      container_name: acme_mysql
      expose:
          - 3306
      volumes:
          - database_data:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: fool
          MYSQL_DATABASE: project
          MYSQL_USER: chuck
          MYSQL_PASSWORD: norris
